### ISSUE TITLE
Expo Andorid EAS 빌드 실패

### ISSUE THREAD

**Issue by coffsun** [crossplatformkorea/react-native-kakao-login#392]
### Description

아래와 같이 Expo 플러그인을 구성하고 Android 빌드를 할 때, 오류가 발생하여 최종적으로 빌드가 실패합니다.
kotlinVersion은 최소 1.6.10 버전 경고로 `1.6.10`, `1.7.10`, `1.8.10`, `1.8.22`를 테스트하였지만 실패하였습니다.
### 플러그인 구성
```
{
  "expo": {
    ...
    "plugins": [
      ...,
      [
        "@react-native-seoul/kakao-login",
        {
          "kakaoAppKey": "",
          "overrideKakaoSDKVersion": "2.9.0", 
          "kotlinVersion": "1.8.10"
        }
      ]
    ],
    ...
  }
} 
```

### 발생한 오류
<img width="951" alt="스크린샷 2023-11-30 오후 8 50 39" src="https://github.com/crossplatformkorea/react-native-kakao-login/assets/34394699/82b43d91-6ae3-415b-aca9-673c6e79dde0">

### Steps to reproduce

1. `npm install @react-native-seoul/kakao-login` 설치
2. Expo 플러그인 구성
3. `npx expo run:android` or `eas build -p android`

### Snack or a link to a repository

.

### React Native Kakao Login version

5.3.1

### React Native version

0.72.6

### Platforms

Android

### JavaScript runtime

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by choiuhana** [comment]
EXPO 49 이신가요?
저같은경우 코틀린버전 1.9.0으로 수정 후 빌드 성공했습니다.

**Comment by coffsun** [comment]
@choiuhana 
우와...! 감사합니다!!!
말씀해주신 버전으로 진행하니까 잘 빌드가 됩니다 ㅜㅜ
정말 감사해요!!!

```
"plugins": [
      [
        "@react-native-seoul/kakao-login",
        {
          "kakaoAppKey": "",
          "kotlinVersion": "1.9.0"
        }
    ]
 ]
```

**Comment by coffsun** [comment]
@choiuhana 
해당 부분은 제가 문서 업데이트 요청드리겠습니다 :) 
다시 한번 진심으로 감사합니다!

**Comment by misssim29** [comment]
선생님 감사합니다 하루종일 헤매던거 해결했습니다 ㅠㅠㅠ

**Comment by misssim29** [comment]
빌드는 되는데 혹시 로그인데이터도 불러와지셨나요?

**Comment by diceros-soojungkim** [comment]
혹시 새로운 코틀린 버전으로 업데이트 해야하는건가요? 1.9.0도 안되는 듯합니다 .

**Comment by YongJaeHyun** [comment]
Expo v53에서는 코틀린 2.0.21 버전으로 성공했습니다
참고하시면 좋을 것 같습니다!

**Comment by myeongjae-kim** [comment]
expo 52.0.47은 코틀린 1.9.25로 됩니다.

**Comment by bnslope** [comment]
expo 53에선 이렇게 하니 되네요.

`
[
      "expo-build-properties",
      {
        "android": {
          "minSdkVersion": 24,
          "kotlinVersion": "2.0.21",
          "extraMavenRepos": [
            "https://devrepo.kakao.com/nexus/content/groups/public/"
          ]
        }
      }
]
`
