### ISSUE TITLE
Kakao SDK의 iOS Privacy Manifest 지원 적용 (24.05.01 까지)

### ISSUE THREAD

**Issue by YangJonghun** [crossplatformkorea/react-native-kakao-login#402]
### Description

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api
24년 5월 1일부터 적용되는 위 내용에 대한 대응처리가 필요하기 때문에 [공지](https://devtalk.kakao.com/t/notice-ios-privacy-manifest-we-support-privacy-manifest-for-ios-apps/136069)내용에 맞춰  iOS SDK버전을 수정해야합니다.

nit) [React Native discussion](https://github.com/react-native-community/discussions-and-proposals/discussions/776#discussioncomment-9098470)의 작업 방향이 결정되면 example도 업데이트 되면 좋을 것 같습니다.

### Steps to reproduce

이는 버그가 아니라 요청사항입니다. 따라서 reproduce는 생략합니다.

### Snack or a link to a repository

https://devtalk.kakao.com/t/notice-ios-privacy-manifest-we-support-privacy-manifest-for-ios-apps/136069

### React Native Kakao Login version

5.3.1

### React Native version

0.73.0

### Platforms

iOS

### JavaScript runtime

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by kentakang** [comment]
#401 PR 적용을 통해 대응이 완료된 것으로 보입니다.

**Comment by YangJonghun** [comment]
@kentakang 
넵 감사합니다 resolve 처리할게요:)
